#ifndef NUMERIC_REPLIES_HPP
#define NUMERIC_REPLIES_HPP

// TODO (maybe?): add description of the errors
// GENERAL ERRORS
#define ERR_UNAVAILRESOURCE		437
#define ERR_NEEDMOREPARAMS		461
#define ERR_ALREADYREGISTERED	462
#define ERR_RESTRICTED			464
// NICK ERRORS
#define ERR_NONICKNAMEGIVEN		431
#define ERR_ERRONEUSNICKNAME	432
#define ERR_NICKNAMEINUSE		433
#define ERR_NICKCOLLISION		436


#endif